### ISSUE TITLE
on_document_created example fails: time date does 

### ISSUE THREAD

**Issue by jelling** [firebase/firebase-functions-python#105] opened 2023-06-16 00:42 UTC
Using the simplest possible example for `on_document_created` returns this error:

`ValueError: time data '2023-06-16T00:34:08.115125300Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'`

Function:

```
@firestore_fn.on_document_created(document="messages/{pushId}")
def makeuppercase(
    event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None],
) -> None:
    print("foo")
    return
```

Full error:

```
 functions: Beginning execution of "us-central1-makeuppercase"
>  2023-06-16 00:34:09,461 - 31024 - app.py-app:1414 - ERROR: Exception on /functions/projects/ [POST]
>  Traceback (most recent call last):
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
>      response = self.full_dispatch_request()
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
>      rv = self.handle_user_exception(e)
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
>      rv = self.dispatch_request()
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
>      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\functions_framework\__init__.py", line 174, in view_func
>      function(event)
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\firebase_functions\firestore_fn.py", line 302, in on_document_created_wrapped
>      return _firestore_endpoint_handler(
>    File "D:\dev\rbt\ml\functions\venv\lib\site-packages\firebase_functions\firestore_fn.py", line 114, in _firestore_endpoint_handler
>      event_time = _dt.datetime.strptime(
>    File "C:\Users\jonat\.pyenv\pyenv-win\versions\3.10.6\lib\_strptime.py", line 568, in _strptime_datetime
>      tt, fraction, gmtoff_fraction = _strptime(data_string, format)
>    File "C:\Users\jonat\.pyenv\pyenv-win\versions\3.10.6\lib\_strptime.py", line 349, in _strptime
>      raise ValueError("time data %r does not match format %r" %
>  ValueError: time data '2023-06-16T00:34:08.115125300Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

**Comment by mattsday** [comment] 2023-06-16 10:24
I also hit this on Linux with Python 3.11 - exact same error.

**Comment by Salakar** [comment] 2023-06-19 10:27
Duplicate of #95, closing in favor of this one.

**Closed by Salakar** 2023-06-19 10:27 UTC
