### ISSUE TITLE
Concurrency is set to 80 by default

### ISSUE THREAD

**Issue by andreas-thomik** [firebase/firebase-functions-python#202] opened 2024-05-03 13:12 UTC
# Description
According to the documentation, a default function has a memory of 256MB (which translates to .167 vCPU according to [this](https://cloud.google.com/functions/docs/configuring/memory)).

```python
    memory: int | MemoryOption | Expression[int] | _util.Sentinel | None = None
    """
    Amount of memory to allocate to a function.
    A value of ``RESET_VALUE`` restores the defaults of 256MB.
    """
 
    ...

    concurrency: int | Expression[int] | _util.Sentinel | None = None
    """
    Number of requests a function can serve at once.
    Can be applied only to functions running on Cloud Functions (2nd gen).
    A value of ``RESET_VALUE`` restores the default concurrency (80 when CPU >= 1, 1 otherwise).
    Concurrency cannot be set to any value other than 1 if `cpu` is less than 1.
    The maximum value for concurrency is 1,000.
    """
```

However, when creating a function with a default setup like that
```python
from firebase_functions import https_fn

@https_fn.on_call()
def test_func():
    return None
```

We end up with a concurrency of 80:
![image](https://github.com/firebase/firebase-functions-python/assets/10515764/81aae34a-e206-4ea7-a64c-833586c58620)

**Comment by exaby73** [comment] 2024-05-06 15:53
Hello @andreas-thomik. This is working as intended. If you see the `cpu` parameter, it defaults to 1, which makes the `concurrency` default to 1 as well:

```python
    cpu: int | _typing.Literal["gcf_gen1"] | _util.Sentinel | None = None
    """
    Fractional number of CPUs to allocate to a function.
    Defaults to 1 for functions with <= 2GB RAM and increases for larger memory sizes.
    This is different from the defaults when using the gcloud utility and is different from
    the fixed amount assigned in Cloud Functions (1st gen).
    To revert to the CPU amounts used in gcloud or in Cloud Functions (1st gen), set this
    to the value "gcf_gen1"
    """
```

Since this is working as intended, I will close this issue. Thank you

**Closed by exaby73** 2024-05-06 15:53 UTC
